---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values (slide 21)
ratings %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(bins = 10, color = 'white', fill = 'indianred1') +
  scale_y_continuous(label = comma) +
  ylab('Number of Ratings') + 
  xlab('Rating Level') + 
  ggtitle('Distribution of Ratings')
 ```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings

ratings_by_movie <- ratings %>%
  group_by(movie_id) %>%
  mutate(mean_rating = mean(rating),
         count = n()
         )
# hint: use the n() function for easy counting within a group
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
ratings_by_movie %>%
  ggplot(aes(x = movie_id)) + 
  geom_histogram(bins = 20, color = 'white', fill = 'indianred1') +
  xlab('Movie ID') +
  ylab('Number of Ratings') +
  ggtitle('Distribution of Movie Popularity') + 
  scale_x_log10(label = comma) + 
  scale_y_continuous(label = comma)
# hint: try scale_x_log10() for a logarithmic x axis
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie (slide 23)
ratings_by_movie %>%
  ggplot(aes(x = mean_rating)) + 
  geom_histogram(bins = 20, color = 'white', fill = 'indianred1') + 
  xlim(c(1.5,5)) + 
  ylab('Number of Movies') +
  xlab('Average Rating') + 
  ggtitle('Distribution of Mean Ratings by Movie')
# hint: try geom_histogram and geom_density
```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves (slide 25)
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

cdf <- ratings_by_movie %>% 
  select(movie_id,count) %>%
  arrange(desc(count)) %>%
  unique() %>%
  ungroup() %>%
  mutate(rank = rank(desc(count)),
         cdf = cumsum(count) / sum(count)
  )

# plot the CDF of movie popularity

cdf %>%
  ggplot(aes(x = rank, y = cdf)) +
  geom_line() +
  scale_y_continuous(label = percent) + 
  ylab('Cumulative Percent of Ratings') + 
  xlab('Movie Rank') + 
  ggtitle('Cumulative Movie Rank')
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings

ratings_by_user <- ratings %>%
  group_by(user_id) %>%
  summarize(mean = mean(rating), count = n())
  
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>%
  ggplot(aes(x = user_id)) + 
  geom_histogram(bins = 100, color = 'white', fill = 'indianred1') + 
  scale_y_continuous(label = comma) +
  scale_x_log10(label = comma) + 
  ylab("Number of Ratings") + 
  xlab('User ID') +
  ggtitle('Distribution of User Activity')
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
num_ratings_per_movies <- ratings %>%
  group_by(movie_id) %>%
  summarize(num_ratings = n()) %>%
  mutate(rank = rank(desc(num_ratings))) %>%
  ungroup()


ratings_plus <- inner_join(ratings, num_ratings_per_movies, by = "movie_id") %>% 
  arrange(movie_id)

# movie id, rating, user id, count, num_ratings, rank (popularity)
ratings_by_top_users <- ratings_plus %>%
  group_by(user_id) %>%
  mutate(count = n()) %>%
  filter(count >= 10) %>%
  ungroup()

hundred_cdf <- ratings_by_top_users %>%
  group_by(user_id) %>%
  arrange(rank) %>%
  summarize(inventory_size = last(rank)) %>%
  ungroup() %>%
  group_by(inventory_size) %>% #
  summarize(num_people_satisfied = n()) %>% #
  arrange(inventory_size) %>% # 
  mutate(cdf = cumsum(num_people_satisfied) / sum(num_people_satisfied))

#ninety_cdf <- ratings_plus %>%
#  group_by(user_id) %>%
#  mutate(count = n()) %>%
#  filter(count >= 10) %>%
#  ungroup() %>%
#  group_by(user_id) %>%
#  summarize(rank_of_lowest_rating = quantile(rank, probs = .90)) %>% # NOTE: in this context, it's the rank of the cut-off movie for the lowest 10% of ratings per user, not the rank of the lowest rating per user

ninety_cdf <- ratings_by_top_users %>%
  group_by(user_id) %>%
  arrange(rank) %>%
  summarize(inventory_size = quantile(rank, probs = .90)) %>%
  ungroup() %>%
  group_by(inventory_size) %>% #
  summarize(num_people_satisfied = n()) %>% #
  arrange(inventory_size) %>% # 
  mutate(cdf = cumsum(num_people_satisfied) / sum(num_people_satisfied))
  
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows:AN INDIVIDUAL USER IS SATISFIED P% OF
# THE TIME AT INVENTORY OF SIZE K IF AT LEAST P% OF THE MOVIES THEY
# RATED ARE CONTAINED IN THE TOP K MOST POPULAR MOVIES.
##### so 100% satisfaction = 100% of the movies
# a user rated are contained in the "top K popular movies" (
# since k is inventory size that's just the size of the catalog) = 
# rank of lowest rated movie is included in the catolog
##### so 90% satisfaction = 90% of the movies
# a user rated are contained in the 
# As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

hundred_cdf %>% 
  ggplot(aes(x = inventory_size, y = cdf)) + 
  geom_line() + 
  geom_line(data = ninety_cdf, 
            aes(x = inventory_size, y = cdf),
            color = 'blue') + 
  geom_vline(xintercept = 3000, linetype = 'dashed', color = 'red') + 
  ylab('Percent of Users Satisfied') + 
  xlab('Inventory Size') +
  scale_y_continuous(label = percent) +
  ggtitle('Anatomy of Long Tails')
```
